### ISSUE TITLE
Install locator package

### ISSUE THREAD

**Issue by ross3102** [sandboxnu/seitz-ui#6]
https://www.locatorjs.com/

* ensure locator works with Vue
* add it to the project so that the team can use it
  * make sure it won't work in prod? (or don't worry about it for now if it's not obvious)

**Comment by mathenachan** [comment]
![Image](https://github.com/sandboxnu/seitz-ui/assets/66972051/3a83c3a7-3342-4459-9f08-2d55a798f327)
